version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    command: ["-c", "listen_addresses=0.0.0.0"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mynetwork

  job_search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_search_container
    depends_on:
      - db
    volumes:
      - job_search_data:/app/data  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
  job_search_data:
